[env]
SERVER_PORT = "8000"

NETWORK_TABLE_IP = "127.0.0.1"
NETWORK_TABLE_PORT = "5000"
TIME_BETWEEN_RECONNECT_ATTEMPTS = "1000"

DATABASE_PATH = "middle_storage.db"
DATABASE_MIN_TIME_AFTER_UPDATE = "1000000" # will store the last 30 sec of the data